### ISSUE TITLE
Any possibility for providing pre-trained models?

### ISSUE THREAD

**Issue by montanaflynn** [tnq177/transformers_without_tears#2]
It would make it more accessible to those without resources to train their own models.

**Comment by tnq177** [comment]
@montanaflynn hi, this was my work during internship at amazon so I don't have access to any of those pretrained models (this code was actually re-implemented, not the one I used at amazon). For future work, I'll try to release pretrained models.

**Comment by montanaflynn** [comment]
Thanks for the reply and also the great code / paper, it's very helpful even without the models!
