### ISSUE TITLE
Question about init methods.

### ISSUE THREAD

**Issue by huu4ontocord** [tnq177/transformers_without_tears#5]
Hi anh @tnq177 , you have two types of init in your code as I can tell.

the sqrt(2/(5D)) for the attention, which you described in the paper.
https://github.com/tnq177/transformers_without_tears/blob/25026061979916afb193274438f7097945acf9bc/layers.py#L34

and another one at:

https://github.com/tnq177/transformers_without_tears/blob/25026061979916afb193274438f7097945acf9bc/layers.py#L116
```
        mean = 0
        std = (2 / (self.ff_dim + self.embed_dim)) ** 0.5
        nn.init.normal_(self.in_proj.weight, mean=mean, std=std)
        nn.init.normal_(self.out_proj.weight, mean=mean, std=std)

```
What is the reasoning for the second init method?

Thank you.

**Comment by tnq177** [comment]
hi,  the 2nd one is Xavier initialization which is a common way to init neural nets.

**Comment by huu4ontocord** [comment]
Thank you for the answer, and thank you anh for this great repo.
